### ISSUE TITLE
Crashes due to E916: not a valid job

### ISSUE THREAD

**Issue by jonathanmcelroy** [airblade/vim-gitgutter#735]
> What is the latest commit SHA in your installed vim-gitgutter?
94ee004087525d4adb56e9325320053fddef0564

> What vim/nvim version are you on?
vim 8.0 +job +channel

On Windows, when using gvim with async enabled, I constantly get an E916 error. I believe it is in [these lines](https://github.com/airblade/vim-gitgutter/blob/94ee004087525d4adb56e9325320053fddef0564/autoload/gitgutter/async.vim#L85-L87). For some reason, ch_getjob is returning "no process" and job_status is failing on that.

I was able to resolve the error for now by removing the checks for the exit_code and have it always call the handler, but I don't know if that will work in all cases.

**Comment by airblade** [comment]
The docs for `ch_getjob()` say:

```
ch_getjob({channel})						*ch_getjob()*
		Get the Job associated with {channel}.
		If there is no job calling |job_status()| on the returned Job
		will result in "fail".
```

So this sounds like a vim bug.  What is your vim patchlevel?  This [similar sounding bug](https://github.com/vim/vim/issues/1242), for instance, was fixed in 8.0.0087.

This code in a couple of years old now.  Maybe a better way to write job exit handlers has emerged since then.  I'll have a look around and see if the code can be changed (in the hope of avoiding your E916 error).

**Comment by airblade** [comment]
I haven't found any significantly different ways to write the exit handler.

One can either use the `close_cb` option or the `exit_cb` option in the job options (in vim).  But I think the `close_cb` is called earlier than the `exit_cb` so it's the better one to use.

However I just noticed in `job_start`'s docs:

```
Note that the job object will be deleted if there are no
references to it.  This closes the stdin and stderr, which may
cause the job to fail with an error.
```

My code doesn't keep a reference to the running job.  This has never caused any problems for me (on macOS) but maybe this is causing the errors you are seeing?

**Comment by jonathanmcelroy** [comment]
I was on gvim version 8.0.0067. After updating to 8.2.0012, the issue persists.

**Comment by airblade** [comment]
Does this patch fix the problem?

```diff
diff --git i/autoload/gitgutter/async.vim w/autoload/gitgutter/async.vim
index 1cc2b16..bb15398 100644
--- i/autoload/gitgutter/async.vim
+++ w/autoload/gitgutter/async.vim
@@ -6,6 +6,8 @@ let s:available = has('nvim') || (
       \   )
       \ )
 
+let s:jobs = {}
+
 function! gitgutter#async#available()
   return s:available
 endfunction
@@ -28,11 +30,12 @@ function! gitgutter#async#execute(cmd, bufnr, handler) abort
           \   'on_exit':   function('s:on_exit_nvim')
           \ }))
   else
-    call job_start(command, {
+    let job = job_start(command, {
           \   'out_cb':   function('s:on_stdout_vim', options),
           \   'err_cb':   function('s:on_stderr_vim', options),
           \   'close_cb': function('s:on_exit_vim', options)
           \ })
+    let s:jobs[job] = 1
   endif
 endfunction
 
@@ -83,6 +86,7 @@ endfunction
 
 function! s:on_exit_vim(channel) dict abort
   let job = ch_getjob(a:channel)
+  unlet s:jobs[job]
   while 1
     if job_status(job) == 'dead'
       let exit_code = job_info(job).exitval
```

**Comment by airblade** [comment]
I have merged this in 4477570.  I'll assume your problem is fixed unless I hear otherwise from you.
